version: '2'
services:
  users:
    build: ./userService
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      LOG_LEVEL: info
      TRANSACTION_SERVICE_URL: http://transactions:3001
  transactions:
    build: ./transactionService
    ports:
      - 3001:3001
    environment:
      PORT: 3001
      LOG_LEVEL: info